# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolgezfarm_services',
            old_name='about_rolgezfarm',
            new_name='service_info',
        ),
        migrations.AddField(
            model_name='rolgezfarm_services',
            name='principalfour',
            field=models.CharField(default='principal four', max_length=200),
        ),
        migrations.AddField(
            model_name='rolgezfarm_services',
            name='principalone',
            field=models.CharField(default='principal one', max_length=200),
        ),
        migrations.AddField(
            model_name='rolgezfarm_services',
            name='principalthree',
            field=models.CharField(default='principal three', max_length=200),
        ),
        migrations.AddField(
            model_name='rolgezfarm_services',
            name='principaltwo',
            field=models.CharField(default='principal two', max_length=200),
        ),
    ]
