# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170904_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolgezfarm_contacts',
            name='name',
            field=models.CharField(default='Rolgezfarm Contact Info', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolgezfarm_services',
            name='name',
            field=models.CharField(default='Rolgezfarm Services', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolgezfarm_services',
            name='principalfour',
            field=models.CharField(default='Principal Four', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolgezfarm_services',
            name='principalone',
            field=models.CharField(default='Principal One', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolgezfarm_services',
            name='principalthree',
            field=models.CharField(default='Principal Three', max_length=200),
        ),
        migrations.AlterField(
            model_name='rolgezfarm_services',
            name='principaltwo',
            field=models.CharField(default='Principal Two', max_length=200),
        ),
    ]
