# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170904_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolgezfarm_services',
            old_name='principalfour',
            new_name='principlefour',
        ),
        migrations.RenameField(
            model_name='rolgezfarm_services',
            old_name='principalone',
            new_name='principleone',
        ),
        migrations.RenameField(
            model_name='rolgezfarm_services',
            old_name='principalthree',
            new_name='principlethree',
        ),
        migrations.RenameField(
            model_name='rolgezfarm_services',
            old_name='principaltwo',
            new_name='principletwo',
        ),
    ]
